site_name: Dokument 
nav:
  - Starseite: index.md
  - Server:
    - Postgresql: Server/Postgresql.md
    - Kachelserver:
      - Server20.04: Server/Kachelserver/Server204.md
      - Server22.04:  Server/Kachelserver/Server224.md
      - Server24.04: Server/Kachelserver/Server244.md
    - Apache-Server mit Nginx verbinden: Server/Apache_Nginx.md
    - Nginx SSL Zertifikat: Server/Nginx_SSL.md
    - Nginx Einstellung: Server/nginx.md
    - Weiter Software: Server/Software.md
  - Forgejo: Server/Forgejo.md
  - IDE: IDE/index.md  
  - Mediawiki: 
    - Installieren: CMS/Mediawiki/index.md
    - Backup: CMS/Mediawiki/Backup.md
    - Wiedererstellen: CMS/Mediawiki/Wiederherstellen.md
  - Xwiki: CMS/Xwiki/Xwiki.md
  - Tools:
    - Pandoc: Tools/Pandoc.md
    - Analysetool: Tools/Analysetool.md
    - Benchmark: Tools/Benchmark.md
  - Archiv:
    - Ollama: Archiv/ollama.md
  - Impressum: Impressum.md
  - Datenschutz: Datenschutz.md

theme:
  name: 'material'
  language: de
plugins:
  - search
extra:
  consent:
    title: Cookie-Zustimmung
    description: >-
      Wir verwenden Cookies, um Ihre Besuche und Präferenzen zu erkennen und die
      Effektivität unserer Dokumentation zu messen.